version: "3.9"

services:
  gateway:
    build: ./api
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    environment:
      MODELS_CONFIG: /config/models.yaml
    volumes:
      - ./config/models.yaml:/config/models.yaml:ro
